{
    'name': 'Thông tin nhân viên + Từ chức/nghỉ việc',
    'version': '1.0',
    'category': 'HR',
    'sequence': '12',
    'author': 'HaiNguyenNgoc',
    'depends': [
        'hr',
    ],
    'data': [
        'data/decision_resignation/data_attachment.xml',
        # 'data/cron.xml',
        # 'security/security_ctv.xml',
        'security/ir.model.access.csv',
        'views/hr_employee.xml',
        'views/hr_resignation.xml',
        # 'views/crm_lead.xml',
        # 'views/source_ctv_contract.xml',
        # 'views/commission_ctv.xml',
        # 'views/ctv_rank.xml',
        # # 'views/view_source_ctv_products.xml',
        # 'wizard/create_ctv.xml',
        # 'wizard/ctv_use_gift.xml',
        # # 'wizard/check_partner.xml',
        # # 'wizard/bao_cao_doanh_so_thang_ctv/collaborator_report.xml',
        # 'views/menu_ctv.xml',
        # 'views/utm_source.xml',
        # # 'wizard/cancel_service_view.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
