version: '2'
services:
  db:
    image: postgres:10.7
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    ports:
      - "54326:5432"
    restart: always             # run as a service

  odoo12:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "12183:8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - ./custom-addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - ./addons:/usr/lib/python3/dist-packages/odoo/addons
    restart: always             # run as a service
